### ISSUE TITLE
Screen protection over "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [ninjinskii/Cavity#41]
Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature. I don't want show my wines collection to other apps. Below an implementation example.

![271815693-2e7d379a-c81c-41b1-88d2-7170fc429af7](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8177e581-55ce-4aab-b2ed-41fb7fc3c1d8)

![1000042037](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/de821f85-2361-437f-95be-fc2a4783ff54)

![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)

**Comment by ninjinskii** [comment]
Ok, i will look into this, but not right now
I'm currently in the process of migrating to fdroid store because google play is such a pain in the ***

**Comment by ninjinskii** [comment]
Some requested features will be available in the next release, lease note that the update will only be available on F droid store

**Comment by ninjinskii** [comment]
Done as part of version 1.7.0, available on F-Droid store soon or with apk in release section
