### ISSUE TITLE
Add a torch option (on/off toggle) somewhere

### ISSUE THREAD

**Issue by serrq** [ninjinskii/Cavity#42]
...while capturing a wine bottle through the camera.

![1000117980](https://github.com/user-attachments/assets/5b32f606-b1b6-415f-ab6f-8e75fed207c1)

**Comment by ninjinskii** [comment]
I'll look into this.
Also, if you're comfortable enough with english, do not hesitate to point fingers at weird english transations, i'm not a native speaker.
Especially when it comes to wine technical terms

**Comment by ninjinskii** [comment]
Done as part of version 1.7.0, available on F-Droid store soon or with apk in release section
