### ISSUE TITLE
Add a 'favorites' section

### ISSUE THREAD

**Issue by serrq** [ninjinskii/Cavity#45]
To easily find your favorite bottles.

**Comment by ninjinskii** [comment]
You can already do that in the Search part of the app, take a look at the third item of the third line of chips in search filters

**Comment by ninjinskii** [comment]
Try clicking on the top right most icon, it will show filters.
On my screen shot favorites are named 'coup de coeurs'
![image](https://github.com/user-attachments/assets/661c9cdf-65fd-4866-98d2-e730509416a5)

**Comment by ninjinskii** [comment]
I don't get it :)
