### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [ninjinskii/Cavity#55]
As already mentioned in #53 (any chance for the badge to be added?), your app is listed at IzzyOnDroid. And with the latest update, the scanners kicked in again and reported:

```
! repo/com.louis.app.cavity_29.apk declares sensitive permission(s): android.permission.CAMERA
  android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_IMAGES
```

Could you please clarify what they are needed/used for? I assume CAMERA is to take photos of special treasures (maybe even reading Barcodes from bottles?) – and storage is for importing from other photos? Might be good to mention that in the `PRIVACY.md` – and at IzzyOnDroid we'd like to add them, with the proper explanation, to the app's "green list" for transparency :wink:

Thanks in advance!

**Comment by ninjinskii** [comment]
Exactly
Agreed, i will add a todo to add both the badge & explanations about permissions usage

**Comment by IzzySoft** [comment]
Thanks! Added the permissions to the app's "green list" here with the proper description then (already live).

I leave the issue open for your "todo". You can of course close it when you no longer need the reminder :wink:

**Comment by ninjinskii** [comment]
One thing tho is that i still have the tracking anti feature flag on my app.
Note that sentry has been made "opt out" from version 1.6.2

**Comment by IzzySoft** [comment]
> "opt out"

That's why. It's on by default, without "informed consent". If it's "opt in", the anti-feature can be removed.

**Comment by ninjinskii** [comment]
I meant it is opt in now, i did mistake in my earlier message
I made it opt in to avoid anti feature flag on fdroid, which i dont have anymore

**Comment by IzzySoft** [comment]
Ah, nice! Thanks! Put Sentry to the app's "green list" then and removed the AF (effective with the next sync around 7 pm UTC).
